# Generated by Django 3.1.7 on 2021-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='test', max_length=64)),
                ('password', models.CharField(default='123456', max_length=64)),
            ],
        ),
    ]
