# Generated by Django 3.1.2 on 2021-04-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
