# Generated by Django 3.1.2 on 2021-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_goodsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goodID',
            field=models.CharField(default='00001', max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodspic',
            field=models.ImageField(default='default.jpg', upload_to='upload/'),
        ),
    ]
